/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2009 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Data declarations

extern _UNKNOWN start; // weak

//-------------------------------------------------------------------------
// Function declarations

_DWORD __cdecl sub_402408(_DWORD, _DWORD, char); // weak
// int __usercall sub_40242A<eax>(int a1<edx>, size_t a2<ecx>, int a3<ebp>, int a4<edi>, int a5<esi>, char start);
// unsigned int __usercall sub_402436<eax>(int a1<eax>, unsigned int a2<edx>, int a3);
int __stdcall sub_40245A(char *filename, const char **argv, const char **envp); // idb
int __stdcall loc_402531(char *filename, const char **argv, const char **envp); // weak
// void __usercall sub_40254E(int a1<esi>, int a2, int a3, int (__cdecl *a4)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD), int a5, int a6, const char **envp, const char **argv);
int __cdecl loc_4026F2(int, int, int, int, int, const char **envp, const char **argv); // weak
// int __usercall sub_40276E<eax>(unsigned int a1<eax>, int a2<edx>);
// char __usercall sub_40277F<al>(unsigned int a1<eax>, unsigned int a2<ecx>, int a3<edi>);


//----- (00402273) --------------------------------------------------------
#error "402273: call analysis failed (funcsize=1)"

//----- (00402408) --------------------------------------------------------
#error "402409: positive sp value has been found (funcsize=1)"

//----- (0040242A) --------------------------------------------------------
int __usercall sub_40242A<eax>(int a1<edx>, size_t a2<ecx>, int a3<ebp>, int a4<edi>, int a5<esi>, char start)
{
  return old_mmap(&start, a2, a1, a5, a4, a3);
}

//----- (00402436) --------------------------------------------------------
unsigned int __usercall sub_402436<eax>(int a1<eax>, unsigned int a2<edx>, int a3)
{
  int v3; // ecx@1
  int v4; // ebx@1
  int v5; // eax@2
  unsigned int result; // eax@4

  v4 = a1;
  v3 = a3;
  do
  {
    v5 = a2 & 0x1F;
    if ( (_BYTE)v5 > 0x19u )
      v5 -= 43;
    --v4;
    *(_BYTE *)v4 = v5 + 65;
    result = a2 >> 5;
    a2 >>= 5;
    --v3;
  }
  while ( v3 );
  return result;
}

//----- (0040245A) --------------------------------------------------------
int __stdcall sub_40245A(char *filename, const char **argv, const char **envp)
{
  int ebp0; // ebp@0
  int v4; // esi@1
  int v5; // eax@2
  int v6; // eax@3
  int v7; // eax@3
  struct flock *v8; // edx@3
  int v9; // eax@3
  int v10; // ST04_4@3
  int v11; // edx@3
  size_t v12; // ecx@3
  int v13; // ST1C_4@3
  int v14; // eax@4
  int v15; // eax@6
  int v16; // eax@7
  int v18; // [sp+0h] [bp-6Ch]@3
  const char file[4]; // [sp+40h] [bp-2Ch]@2
  int v20; // [sp+44h] [bp-28h]@2

  v4 = sys_open(filename, 0, 0);
  if ( v4 >= 0 )
  {
    *(_DWORD *)file = 1869770799;
    v20 = 12131;
    __asm { int     80h             ; LINUX - sys_getpid }
    v5 = sub_40276E(0x14u, (int)((char *)&v20 + 2));
    *(_DWORD *)v5 = 795108911;
    sub_40276E(v4, v5 + 4);
    if ( !sys_access(file, 5) )
    {
      v6 = sys_unlink(filename);
      v7 = sys_fcntl(v4, 2, v8);
      v9 = sys_execve(file, argv, envp);
      v10 = sys_lseek(v4, 0, 2);
      v13 = sub_40242A(v11, v12, ebp0, v10, v4, 0);
      v18 = sys_open(filename, 193, 0x1C0u);
      if ( v10 != sys_write(v18, (const void *)v13, v10) )
      {
        v14 = sys_exit(127);
        JUMPOUT(*(int *)loc_402531);
      }
      v15 = sys_close(v18);
    }
    v16 = sys_close(v4);
  }
  return v4;
}
// 402531: using guessed type int __stdcall loc_402531(char *filename, const char **argv, const char **envp);

//----- (0040254E) --------------------------------------------------------
void __usercall sub_40254E(int a1<esi>, int a2, int a3, int (__cdecl *a4)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD), int a5, int a6, const char **envp, const char **argv)
{
  int ebp0; // ebp@0
  int v9; // eax@2
  unsigned int v10; // eax@2
  int v11; // ST24_4@2
  int v12; // eax@2
  int v13; // edx@4
  size_t v14; // ecx@4
  int v15; // edx@5
  size_t v16; // ecx@5
  int v17; // eax@18
  int v18; // edx@18
  int v19; // eax@19
  int v20; // eax@20
  int v21; // eax@24
  int v22; // eax@24
  int v23; // [sp+10h] [bp-78h]@5
  int v24; // [sp+1Ch] [bp-6Ch]@4
  int v25; // [sp+30h] [bp-58h]@14
  struct timeval tv; // [sp+34h] [bp-54h]@2
  int len; // [sp+3Ch] [bp-4Ch]@7
  unsigned int v28; // [sp+40h] [bp-48h]@7
  int v29; // [sp+44h] [bp-44h]@7
  const char filename[4]; // [sp+4Ch] [bp-3Ch]@2
  int v31; // [sp+50h] [bp-38h]@2
  char v32; // [sp+5Bh] [bp-2Dh]@2
  char v33; // [sp+5Fh] [bp-29h]@2
  int v34; // [sp+6Ch] [bp-1Ch]@1
  off_t off; // [sp+70h] [bp-18h]@1
  unsigned int v36; // [sp+74h] [bp-14h]@1
  int v37; // [sp+90h] [bp+8h]@1
  int v38; // [sp+90h] [bp+8h]@7
  int v39; // [sp+94h] [bp+Ch]@1
  const void *v40; // [sp+94h] [bp+Ch]@7

  v34 = *(_DWORD *)a3;
  off = *(_DWORD *)(a3 + 4);
  v36 = *(_DWORD *)(a3 + 8);
  v37 = a2 - 12;
  v39 = a3 + 12;
  if ( v34 == 1475169751 )
  {
    *(_DWORD *)filename = 1886221359;
    v31 = 2020635951;
    __asm { int     80h             ; LINUX - sys_getpid }
    v10 = sub_402436((int)&v33, 0x14u, 4);
    v33 = 0;
    v11 = v34 ^ v10;
    v12 = sys_gettimeofday(&tv, 0);
    sub_402436((int)&v32, tv.tv_sec ^ v11 ^ (tv.tv_usec << 12), 7);
    v9 = sys_unlink(filename);
    if ( v9 == -2 )
      goto LABEL_27;
    if ( !v9 )
    {
LABEL_27:
      v24 = sys_open((char *)filename, 194, 0x1C0u);
      if ( !sys_ftruncate(v24, off) )
      {
        v23 = sub_40242A(v13, v14, ebp0, (int)&v32, a1, 0);
        if ( (unsigned int)v23 <= 0xFFFFF000 )
        {
          sub_40242A(v15, v16, ebp0, (int)&v32, a1, v23);
          while ( 1 )
          {
            len = *(_DWORD *)v39;
            v28 = *(_DWORD *)(v39 + 4);
            v29 = *(_DWORD *)(v39 + 8);
            v38 = v37 - 12;
            v40 = (const void *)(v39 + 12);
            if ( !len )
              break;
            if ( v28 > len || v28 > v36 )
              goto LABEL_19;
            if ( v28 >= len )
            {
              memcpy((void *)v23, v40, len);
            }
            else
            {
              v25 = len;
              if ( a4(v40, v28, v23, &v25, v29) || v25 != len )
                goto LABEL_19;
            }
            v17 = sys_munmap((void *)v23, len);
            v37 = v38 - v28;
            v23 += v18;
            off -= v18;
            v39 = (int)((char *)v40 + v28);
            if ( v37 < 0 )
              goto LABEL_19;
          }
          if ( v28 == 558649164 )
          {
            if ( !off )
            {
              if ( !sys_close(v24) )
              {
                if ( sub_40245A((char *)filename, argv, envp) >= 0 )
                {
                  __asm { int     80h             ; LINUX - sys_fork }
                  v21 = sys_waitpid(-1, 0, 0);
                  v22 = sys_execve(filename, argv, envp);
                }
              }
            }
          }
        }
      }
LABEL_19:
      v19 = sys_unlink(filename);
    }
  }
  v20 = sys_exit(127);
  JUMPOUT(*(int *)loc_4026F2);
}
// 4026F2: using guessed type int __cdecl loc_4026F2(int, int, int, int, int, const char **envp, const char **argv);

//----- (0040276E) --------------------------------------------------------
int __usercall sub_40276E<eax>(unsigned int a1<eax>, int a2<edx>)
{
  int v3; // edi@1
  char v4; // ah@1

  v3 = a2;
  sub_40277F(a1, 0xAu, a2);
  *(_BYTE *)v3 = v4;
  return v3;
}

//----- (0040277F) --------------------------------------------------------
char __usercall sub_40277F<al>(unsigned int a1<eax>, unsigned int a2<ecx>, int a3<edi>)
{
  char result; // al@3
  int v4; // [sp-4h] [bp-4h]@1

  v4 = (signed int)a1 % (unsigned __int64)a2;
  if ( (unsigned int)((signed int)a1 / (unsigned __int64)a2) )
    sub_40277F(a2, (signed int)a1 % (unsigned __int64)a2);
  result = v4 + 48;
  *(_BYTE *)a3 = v4 + 48;
  return result;
}

#error "There were 2 decompilation failure(s) on 8 function(s)"
