/*

[manizzle@alexandria rev300]$ python2
Python 2.7.3 (default, Apr 24 2012, 00:00:54) 
[GCC 4.7.0 20120414 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> chr(107)
'k'
>>> chr(101)
'e'
>>> chr(99)
'c'
>>> chr(99)
'c'
>>> chr(104)
'h'
>>> chr(97)
'a'
>>> chr(99)
'c'
>>> chr(107)
'k'
>>> chr(121)
'y'
>>> chr(111)
'o'
>>> chr(48)
'0'
>>> chr(117)
'u'
>>> kecchackyo0u


*/

/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2009 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Data declarations

extern _UNKNOWN start; // weak
extern int dword_80499E0; // weak
extern char aXah7nmrcfpdku0[37]; // weak
extern char format[]; // idb
extern char aGreatNowSubmit[]; // idb
extern char aUsageSUserKey[]; // idb
extern char aHackyou[8]; // weak
extern char aErrSomethingWe[]; // idb
extern _DWORD dword_804AB30[48]; // idb
extern _DWORD dword_804AC50[25]; // idb
// extern _UNKNOWN _gmon_start__; weak

//-------------------------------------------------------------------------
// Function declarations

int __cdecl sub_804831C(char a1);
signed int __cdecl sub_804838C(int a1, int a2);
signed int __cdecl sub_804844B(int a1, int a2);
signed int __cdecl sub_804850A(int a1, int a2);
void __cdecl sub_80485C9();
void __cdecl sub_80485F0();
void __cdecl sub_8048617(int a1, int a2);
int __cdecl sub_804875D(int a1, int a2);
int __cdecl sub_8048DC4(int a1, int a2, int a3, int a4);
int *__cdecl sub_8049070();
// signed int __usercall sub_80490F0<eax>(unsigned int a1<eax>, unsigned int a2<edx>, __int64 a3, int a4);
void __cdecl sub_8049460();
void __cdecl sub_8049480();
int __cdecl init_proc();
void __cdecl term_proc();
void __cdecl sub_8049761();
int __cdecl sub_8049A00(_DWORD); // weak
int printf(const char *format, ...);
void exit(int status);
int __cdecl sub_8049A30(_DWORD, _DWORD); // weak
int __cdecl sub_8049A40(_DWORD, _DWORD, _DWORD); // weak
int __cdecl sub_8049A50(_DWORD, _DWORD, _DWORD); // weak


//----- (08048280) --------------------------------------------------------
#error "8048283: positive sp value has been found (funcsize=2)"

//----- (0804831C) --------------------------------------------------------
int __cdecl sub_804831C(char a1)
{
  return aXah7nmrcfpdku0[(unsigned __int8)((((unsigned __int8)(a1 - 99) ^ 0xFE) - 39)
 ^ 0x34)
                       % sub_8049A00("xah7nmrcfpdku0gy62vb4lwzio5j38et1qs9")];
}
// 8049A00: using guessed type int __cdecl sub_8049A00(_DWORD);

//----- (0804838C) --------------------------------------------------------
signed int __cdecl sub_804838C(int a1, int a2)
{
  int v2; // eax@1
  signed int i; // [sp+0h] [bp-54h]@1
  char v5[64]; // [sp+4h] [bp-50h]@1
  int v6; // [sp+44h] [bp-10h]@1
  int v7; // [sp+48h] [bp-Ch]@1
  int v8; // [sp+4Ch] [bp-8h]@1
  int v9; // [sp+50h] [bp-4h]@1

  v6 = 23;
  v7 = 13;
  v8 = 34;
  v9 = 40;
  v2 = sub_8049A00(a1);
  sub_8048DC4(a1, v2, (int)v5, 64);
  for ( i = 0; i < 4; ++i )
  {
    if ( sub_804831C(v5[*(&v6 + i)]) != *(_BYTE *)(i + a2) )
      return 0;
  }
  return 1337;
}
// 
// 8049A00: using guessed type int __cdecl sub_8049A00(_DWORD);
// 804838C: using guessed type char var_50[64];

//----- (0804844B) --------------------------------------------------------
signed int __cdecl sub_804844B(int a1, int a2)
{
  int v2; // eax@1
  signed int i; // [sp+0h] [bp-54h]@1
  char v5[64]; // [sp+4h] [bp-50h]@1
  int v6; // [sp+44h] [bp-10h]@1
  int v7; // [sp+48h] [bp-Ch]@1
  int v8; // [sp+4Ch] [bp-8h]@1
  int v9; // [sp+50h] [bp-4h]@1

  v6 = 10;
  v7 = 20;
  v8 = 45;
  v9 = 49;
  v2 = sub_8049A00(a1);
  sub_8048DC4(a1, v2, (int)v5, 64);
  for ( i = 0; i < 4; ++i )
  {
    if ( sub_804831C(v5[*(&v6 + i)]) != *(_BYTE *)(i + a2) )
      return 0;
  }
  return 1337;
}
// 8049A00: using guessed type int __cdecl sub_8049A00(_DWORD);
// 804844B: using guessed type char var_50[64];

//----- (0804850A) --------------------------------------------------------
signed int __cdecl sub_804850A(int a1, int a2)
{
  int v2; // eax@1
  signed int i; // [sp+0h] [bp-54h]@1
  char v5[64]; // [sp+4h] [bp-50h]@1
  int v6; // [sp+44h] [bp-10h]@1
  int v7; // [sp+48h] [bp-Ch]@1
  int v8; // [sp+4Ch] [bp-8h]@1
  int v9; // [sp+50h] [bp-4h]@1

  v6 = 1;
  v7 = 27;
  v8 = 31;
  v9 = 44;
  v2 = sub_8049A00(a1);
  sub_8048DC4(a1, v2, (int)v5, 64);
  for ( i = 0; i < 4; ++i )
  {
    if ( sub_804831C(v5[*(&v6 + i)]) != *(_BYTE *)(i + a2) )
      return 0;
  }
  return 1337;
}
// 8049A00: using guessed type int __cdecl sub_8049A00(_DWORD);
// 804850A: using guessed type char var_50[64];

//----- (080485C9) --------------------------------------------------------
void __cdecl sub_80485C9()
{
  printf("Are trying to fool me?\n");
  exit(1);
}

//----- (080485F0) --------------------------------------------------------
void __cdecl sub_80485F0()
{
  printf("Great! Now submit the license key for 'hackyou'\n");
  exit(1);
}

//----- (08048617) --------------------------------------------------------
void __cdecl sub_8048617(int a1, int a2)
{
  int v2; // [sp+0h] [bp-8h]@5
  int v3; // [sp+4h] [bp-4h]@5

  if ( a1 != 3 )
  {
    printf("Usage: %s <user> <key>\n", *(_DWORD *)a2);
    exit(1);
  }
  if ( sub_8049A30(*(_DWORD *)(a2 + 4), "hackyou") )
  {
    v3 = *(_DWORD *)(a2 + 4);
    v2 = *(_DWORD *)(a2 + 8);
    if ( sub_8049A00(v2) != 14 )
      sub_80485C9();
    if ( *(_BYTE *)(v2 + 4) == 45 )
    {
      if ( *(_BYTE *)(v2 + 9) == 45 )
      {
        if ( !sub_804838C(v3, v2) )
          sub_80485C9();
        if ( !sub_804844B(v3, v2 + 5) )
          sub_80485C9();
        if ( !sub_804850A(v3, v2 + 10) )
          sub_80485C9();
        sub_80485F0();
      }
    }
    sub_80485C9();
  }
  printf("Err, something went wrong...\n");
  exit(2);
}
// 8049A00: using guessed type int __cdecl sub_8049A00(_DWORD);
// 8049A30: using guessed type int __cdecl sub_8049A30(_DWORD, _DWORD);

//----- (0804875D) --------------------------------------------------------
int __cdecl sub_804875D(int a1, int a2)
{
  int result; // eax@2
  int v3; // edx@5
  int v4; // STA8_4@5
  int v5; // edx@5
  int *v6; // ecx@5
  int *v7; // eax@8
  int v8; // ecx@8
  int v9; // ecx@10
  int v10; // eax@10
  int v11; // edx@12
  int v12; // ecx@14
  int v13; // edx@14
  int v14; // ST68_4@14
  int v15; // eax@14
  int v16; // ST60_4@14
  int v17; // edx@14
  int v18; // ST64_4@14
  int v19; // eax@14
  int v20; // edx@14
  int v21; // edx@19
  int v22; // eax@19
  int v23; // ecx@19
  int *v24; // edx@19
  int *v25; // eax@22
  int v26; // edx@22
  int v27; // eax@22
  int v28; // ecx@22
  int v29; // eax@24
  unsigned int v30; // [sp+E4h] [bp-3Ch]@5
  int v31; // [sp+E8h] [bp-38h]@14
  unsigned int v32; // [sp+10Ch] [bp-14h]@8
  int v33; // [sp+110h] [bp-10h]@8
  int i; // [sp+114h] [bp-Ch]@1
  int k; // [sp+118h] [bp-8h]@8
  int j; // [sp+11Ch] [bp-4h]@3

  for ( i = 0; ; ++i )
  {
    result = i;
    if ( i >= a2 )
      break;
    for ( j = 0; j < 5; ++j )
    {
      v3 = 8 * j + a1;
      v4 = *(_DWORD *)(8 * (j + 15) + a1) ^ *(_DWORD *)(8 * (j + 10) + a1) ^ *(_DWORD *)(8 * (j + 5) + a1) ^ *(_DWORD *)v3;
      v5 = *(_DWORD *)(8 * (j + 20) + a1 + 4) ^ *(_DWORD *)(8 * (j + 15) + a1 + 4) ^ *(_DWORD *)(8 * (j + 10) + a1 + 4) ^ *(_DWORD *)(8 * (j + 5) + a1 + 4) ^ *(_DWORD *)(v3 + 4);
      v6 = (int *)(&v30 + 2 * j);
      *v6 = *(_DWORD *)(8 * (j + 20) + a1) ^ v4;
      v6[1] = v5;
    }
    for ( j = 0; j < 5; ++j )
    {
      v7 = (int *)(&v30 + 2 * (j + 1) % 5);
      v8 = (2 * v7[1] | ((unsigned int)*v7 >> 31)) ^ *(unsigned int *)((char *)&v30 + 2 * (j + 4) % 5 + 4);
      v32 = ((*(unsigned int *)((char *)&v30 + 2 * (j + 1) % 5 + 4) >> 31) | 2 * *v7) ^ *(&v30 + 2 * (j + 4) % 5);
      v33 = v8;
      for ( k = 0; k < 25; k += 5 )
      {
        v9 = v33 ^ *(_DWORD *)(8 * (j + k) + a1 + 4);
        v10 = 8 * (j + k) + a1;
        *(_DWORD *)v10 = v32 ^ *(_DWORD *)(8 * (j + k) + a1);
        *(_DWORD *)(v10 + 4) = v9;
      }
    }
    v11 = *(_DWORD *)(a1 + 12);
    v32 = *(_DWORD *)(a1 + 8);
    v33 = v11;
    for ( j = 0; j < 24; ++j )
    {
      k = dword_804AC50[j];
      v12 = 8 * k + a1;
      v13 = *(_DWORD *)(v12 + 4);
      v30 = *(_DWORD *)v12;
      v31 = v13;
      v14 = 8 * k + a1;
      sub_8049480();
      v16 = v15;
      v18 = v17;
      sub_8049460();
      *(_DWORD *)v14 = v19 | v16;
      *(_DWORD *)(v14 + 4) = v20 | v18;
      v32 = v30;
      v33 = v31;
    }
    for ( k = 0; k < 25; k += 5 )
    {
      for ( j = 0; j < 5; ++j )
      {
        v21 = 8 * (j + k) + a1;
        v22 = *(_DWORD *)v21;
        v23 = *(_DWORD *)(v21 + 4);
        v24 = (int *)(&v30 + 2 * j);
        *v24 = v22;
        v24[1] = v23;
      }
      for ( j = 0; j < 5; ++j )
      {
        v25 = (int *)(&v30 + 2 * (j + 1) % 5);
        v26 = *(&v30 + 2 * (j + 2) % 5) & ~*v25 ^ *(_DWORD *)(8 * (j + k) + a1);
        v27 = *(unsigned int *)((char *)&v30 + 2 * (j + 2) % 5 + 4) & ~v25[1] ^ *(_DWORD *)(8 * (j + k) + a1 + 4);
        v28 = 8 * (j + k) + a1;
        *(_DWORD *)v28 = v26;
        *(_DWORD *)(v28 + 4) = v27;
      }
    }
    v29 = dword_804AB30[2 * i + 1] ^ *(_DWORD *)(a1 + 4);
    *(_DWORD *)a1 ^= dword_804AB30[2 * i];
    *(_DWORD *)(a1 + 4) = v29;
  }
  return result;
}

//----- (08048DC4) --------------------------------------------------------
int __cdecl sub_8048DC4(int a1, int a2, int a3, int a4)
{
  int v4; // ecx@5
  char *v5; // edx@5
  int v6; // ecx@9
  char *v7; // edx@9
  int v9; // [sp+20h] [bp-164h]@1
  int v10; // [sp+24h] [bp-160h]@1
  int i; // [sp+28h] [bp-15Ch]@3
  int j; // [sp+28h] [bp-15Ch]@7
  char v13[144]; // [sp+2Ch] [bp-158h]@7
  char v14[200]; // [sp+BCh] [bp-C8h]@1

  v10 = 200 - 2 * a4;
  v9 = (200 - 2 * a4) / 8;
  sub_8049A40(v14, 0, 200);
  while ( a2 >= v10 )
  {
    for ( i = 0; i < v9; ++i )
    {
      v4 = *(_DWORD *)(8 * i + a1 + 4) ^ *(_DWORD *)&v14[8 * i + 4];
      v5 = &v14[8 * i];
      *(_DWORD *)v5 = *(_DWORD *)(8 * i + a1) ^ *(_DWORD *)&v14[8 * i];
      *((_DWORD *)v5 + 1) = v4;
    }
    sub_804875D((int)v14, 24);
    a2 -= v10;
    a1 += v10;
  }
  sub_8049A50(v13, a1, a2);
  v13[a2] = 1;
  sub_8049A40(&v13[a2 + 1], 0, v10 - (a2 + 1));
  v13[v10 - 1] |= 0x80u;
  for ( j = 0; j < v9; ++j )
  {
    v6 = *(_DWORD *)&v13[8 * j + 4] ^ *(_DWORD *)&v14[8 * j + 4];
    v7 = &v14[8 * j];
    *(_DWORD *)v7 = *(_DWORD *)&v13[8 * j] ^ *(_DWORD *)&v14[8 * j];
    *((_DWORD *)v7 + 1) = v6;
  }
  sub_804875D((int)v14, 24);
  sub_8049A50(a3, v14, a4);
  return 0;
}
// 8049A40: using guessed type int __cdecl sub_8049A40(_DWORD, _DWORD, _DWORD);
// 8049A50: using guessed type int __cdecl sub_8049A50(_DWORD, _DWORD, _DWORD);
// 8048DC4: using guessed type char var_C8[200];
// 8048DC4: using guessed type char var_158[144];

//----- (08049070) --------------------------------------------------------
int *__cdecl sub_8049070()
{
  init_proc();
  return &dword_80499E0;
}
// 80499E0: using guessed type int dword_80499E0;

//----- (080490F0) --------------------------------------------------------
signed int __usercall sub_80490F0<eax>(unsigned int a1<eax>, unsigned int a2<edx>, __int64 a3, int a4)
{
  unsigned int v5; // ecx@1
  unsigned int v6; // ebx@1
  unsigned int v7; // edi@1
  signed int result; // eax@3
  int v9; // edx@3
  unsigned __int64 v10; // qtt@3
  unsigned __int64 v16; // qtt@17
  __int64 v17; // qax@18
  unsigned int v18; // ecx@18
  unsigned int v19; // ebx@18
  unsigned int v20; // ebp@18
  int v21; // edi@18
  unsigned int v22; // eax@18
  unsigned __int64 v23; // qtt@18
  unsigned int v24; // ebx@21
  unsigned int v25; // ebx@23
  unsigned int v26; // [sp+0h] [bp-2Ch]@1
  int v27; // [sp+0h] [bp-2Ch]@18
  unsigned int v28; // [sp+4h] [bp-28h]@1
  unsigned int v29; // [sp+4h] [bp-28h]@18
  int v30; // [sp+8h] [bp-24h]@10
  unsigned int v31; // [sp+Ch] [bp-20h]@18
  int v32; // [sp+10h] [bp-1Ch]@18
  unsigned int v33; // [sp+14h] [bp-18h]@18

  v6 = a2;
  _EDX = HIDWORD(a3);
  v5 = a3;
  v7 = a1;
  v26 = a1;
  v28 = v6;
  if ( HIDWORD(a3) )
  {
    if ( HIDWORD(a3) <= v6 )
    {
      __asm { bsr     edi, edx }
      v30 = _EDI ^ 0x1F;
      if ( _EDI ^ 0x1F )
      {
        v21 = 32 - v30;
        v27 = (HIDWORD(a3) << v30) | ((_DWORD)a3 >> (32 - v30));
        v29 = (_DWORD)a3 << v30;
        v33 = a1 << v30;
        LODWORD(v23) = (v6 << v30) | (a1 >> (32 - v30));
        HIDWORD(v23) = v6 >> (32 - v30);
        v22 = v23 / (unsigned int)v27;
        v19 = v23 % (unsigned int)v27;
        v18 = v22;
        v32 = v23 / (unsigned int)v27;
        v17 = ((_DWORD)a3 << v30) * v22;
        v31 = HIDWORD(v17);
        v20 = HIDWORD(v17);
        HIDWORD(v17) = v17;
        if ( v19 < v20 || (_DWORD)v17 > v33 && v20 == v19 )
        {
          v32 = v18 - 1;
          HIDWORD(v17) = v17 - v29;
          v20 = (__PAIR__(v31, v17) - __PAIR__(v27, v29)) >> 32;
        }
        if ( a4 )
        {
          v24 = (__PAIR__(v19, v33) - __PAIR__(v20, HIDWORD(v17))) >> 32;
          *(_DWORD *)a4 = (v24 << v21) | ((v33 - HIDWORD(v17)) >> v30);
          *(_DWORD *)(a4 + 4) = v24 >> v30;
        }
        result = v32;
      }
      else
      {
        if ( a1 >= (_DWORD)a3 || (result = 0, v6 > HIDWORD(a3)) )
        {
          v25 = (__PAIR__(v6, v26) - a3) >> 32;
          v26 -= a3;
          result = 1;
          v28 = v25;
        }
        if ( a4 )
        {
          *(_DWORD *)a4 = v26;
          *(_DWORD *)(a4 + 4) = v28;
        }
      }
    }
    else
    {
      result = 0;
      if ( a4 )
      {
        *(_DWORD *)a4 = v7;
        *(_DWORD *)(a4 + 4) = v6;
      }
    }
  }
  else
  {
    if ( (_DWORD)a3 <= v6 )
    {
      if ( !(_DWORD)a3 )
        v5 = 1 / 0u;
      LODWORD(v16) = a1;
      HIDWORD(v16) = v6 % v5;
      result = v16 / v5;
      v9 = v16 % v5;
    }
    else
    {
      LODWORD(v10) = a1;
      HIDWORD(v10) = v6;
      result = v10 / (unsigned int)a3;
      v9 = v10 % (unsigned int)a3;
    }
    if ( a4 )
    {
      *(_DWORD *)a4 = v9;
      *(_DWORD *)(a4 + 4) = 0;
    }
  }
  return result;
}

//----- (08049460) --------------------------------------------------------
void __cdecl sub_8049460()
{
  __asm { rep retn }
}

//----- (08049480) --------------------------------------------------------
void __cdecl sub_8049480()
{
  __asm { rep retn }
}

//----- (08049728) --------------------------------------------------------
int __cdecl init_proc()
{
  int result; // eax@1

  result = (int)&_gmon_start__;
  if ( &_gmon_start__ )
    result = v0();
  return result;
}

//----- (0804974C) --------------------------------------------------------
void __cdecl term_proc()
{
  ;
}

//----- (08049761) --------------------------------------------------------
void __cdecl sub_8049761()
{
  ;
}

#error "There were 1 decompilation failure(s) on 17 function(s)"
