/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_about_dialog (void);
GtkWidget* create_componant_choice_dialog (void);
GtkWidget* create_open_fileselection (void);
GtkWidget* create_save_fileselection (void);
GtkWidget* create_heuristic_log (void);
