/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gui_callbacks.h"
#include "gui_interface.h"
#include "gui_support.h"

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *vbox1;
  GtkWidget *handlebox1;
  GtkWidget *main_menubar;
  guint tmp_key;
  GtkWidget *file4;
  GtkWidget *file4_menu;
  GtkAccelGroup *file4_menu_accels;
  GtkWidget *open3;
  GtkWidget *save;
  GtkWidget *exit2;
  GtkWidget *tools1;
  GtkWidget *tools1_menu;
  GtkAccelGroup *tools1_menu_accels;
  GtkWidget *guile_shell;
  GtkWidget *help2;
  GtkWidget *help2_menu;
  GtkAccelGroup *help2_menu_accels;
  GtkWidget *about1;
  GtkWidget *handlebox2;
  GtkWidget *toolbar1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *toolbar_open_button;
  GtkWidget *toolbar_save_button;
  GtkWidget *toolbar_equate_button;
  GtkWidget *toolbar_heuristic_button;
  GtkWidget *toolbar_stop_button;
  GtkWidget *main_notebook;
  GtkWidget *patch_box;
  GtkWidget *hbox9;
  GtkWidget *label1241;
  GtkWidget *patch_combo;
  GtkWidget *patch_combo_entry;
  GtkWidget *hbox10;
  GtkWidget *patch_apply_button;
  GtkWidget *scrolledwindow7;
  GtkWidget *patch_description;
  GtkWidget *hbox8;
  GtkWidget *label1240;
  GtkWidget *pixmap4;
  GtkWidget *vbox2;
  GtkWidget *table1;
  GtkWidget *label6;
  GtkWidget *transform_componant_entry;
  GtkWidget *button1;
  GtkWidget *button3;
  GtkWidget *label7;
  GtkWidget *transform_interface_entry;
  GtkWidget *transform_frame;
  GtkWidget *hbox6;
  GtkWidget *label1237;
  GtkWidget *pixmap2;
  GtkWidget *vbox5;
  GtkWidget *table7;
  GtkWidget *label23;
  GtkWidget *heuristic_componant_entry;
  GtkWidget *label24;
  GtkWidget *heuristic_interface_entry;
  GtkWidget *button37;
  GtkWidget *button38;
  GtkWidget *heuristic_frame;
  GtkWidget *hbox5;
  GtkWidget *label1236;
  GtkWidget *pixmap3;
  GtkWidget *vbox6;
  GtkWidget *table8;
  GtkWidget *label25;
  GtkWidget *fitness_componant_entry;
  GtkWidget *label26;
  GtkWidget *fitness_interface_entry;
  GtkWidget *button39;
  GtkWidget *button40;
  GtkWidget *fitness_frame;
  GtkWidget *hbox4;
  GtkWidget *fitness_label;
  GtkWidget *pixmap1;
  GtkWidget *label4;
  GtkWidget *scrolledwindow1;
  GtkWidget *source_text;
  GtkWidget *label5;
  GtkWidget *scrolledwindow2;
  GtkWidget *view_text;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (main_window, "main_window");
  gtk_object_set_data (GTK_OBJECT (main_window), "main_window", main_window);
  gtk_window_set_title (GTK_WINDOW (main_window), "Crank");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_window), vbox1);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox1, "handlebox1");
  gtk_widget_ref (handlebox1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "handlebox1", handlebox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox1, FALSE, FALSE, 0);

  main_menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (main_menubar, "main_menubar");
  gtk_widget_ref (main_menubar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "main_menubar", main_menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_menubar);
  gtk_container_add (GTK_CONTAINER (handlebox1), main_menubar);

  file4 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file4)->child),
                                   "_File");
  gtk_widget_add_accelerator (file4, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (file4, "file4");
  gtk_widget_ref (file4);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "file4", file4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file4);
  gtk_container_add (GTK_CONTAINER (main_menubar), file4);

  file4_menu = gtk_menu_new ();
  gtk_widget_set_name (file4_menu, "file4_menu");
  gtk_widget_ref (file4_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "file4_menu", file4_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file4), file4_menu);
  file4_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file4_menu));

  open3 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (open3)->child),
                                   "_Open");
  gtk_widget_add_accelerator (open3, "activate_item", file4_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (open3, "open3");
  gtk_widget_ref (open3);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "open3", open3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (open3);
  gtk_container_add (GTK_CONTAINER (file4_menu), open3);

  save = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (save)->child),
                                   "_Save View");
  gtk_widget_add_accelerator (save, "activate_item", file4_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (save, "save");
  gtk_widget_ref (save);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "save", save,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save);
  gtk_container_add (GTK_CONTAINER (file4_menu), save);

  exit2 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit2)->child),
                                   "E_xit");
  gtk_widget_add_accelerator (exit2, "activate_item", file4_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (exit2, "exit2");
  gtk_widget_ref (exit2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "exit2", exit2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit2);
  gtk_container_add (GTK_CONTAINER (file4_menu), exit2);

  tools1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (tools1)->child),
                                   "_Tools");
  gtk_widget_add_accelerator (tools1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (tools1, "tools1");
  gtk_widget_ref (tools1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "tools1", tools1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tools1);
  gtk_container_add (GTK_CONTAINER (main_menubar), tools1);

  tools1_menu = gtk_menu_new ();
  gtk_widget_set_name (tools1_menu, "tools1_menu");
  gtk_widget_ref (tools1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "tools1_menu", tools1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (tools1), tools1_menu);
  tools1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (tools1_menu));

  guile_shell = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (guile_shell)->child),
                                   "_Guile Shell");
  gtk_widget_add_accelerator (guile_shell, "activate_item", tools1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (guile_shell, "guile_shell");
  gtk_widget_ref (guile_shell);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "guile_shell", guile_shell,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (guile_shell);
  gtk_container_add (GTK_CONTAINER (tools1_menu), guile_shell);

  help2 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help2)->child),
                                   "_Help");
  gtk_widget_add_accelerator (help2, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (help2, "help2");
  gtk_widget_ref (help2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "help2", help2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help2);
  gtk_container_add (GTK_CONTAINER (main_menubar), help2);

  help2_menu = gtk_menu_new ();
  gtk_widget_set_name (help2_menu, "help2_menu");
  gtk_widget_ref (help2_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "help2_menu", help2_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help2), help2_menu);
  help2_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help2_menu));

  about1 = gtk_menu_item_new_with_label ("About");
  gtk_widget_set_name (about1, "about1");
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help2_menu), about1);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox2, "handlebox2");
  gtk_widget_ref (handlebox2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "handlebox2", handlebox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox2, FALSE, FALSE, 0);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (handlebox2), toolbar1);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar1), 1);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar1), GTK_RELIEF_NONE);

  tmp_toolbar_icon = create_pixmap (main_window, "open.xpm");
  toolbar_open_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Open",
                                "Open a file into the source area", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (toolbar_open_button, "toolbar_open_button");
  gtk_widget_ref (toolbar_open_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "toolbar_open_button", toolbar_open_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_open_button);

  tmp_toolbar_icon = create_pixmap (main_window, "save.xpm");
  toolbar_save_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Save",
                                "Save the contents of the view area", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (toolbar_save_button, "toolbar_save_button");
  gtk_widget_ref (toolbar_save_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "toolbar_save_button", toolbar_save_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_save_button);

  tmp_toolbar_icon = create_pixmap (main_window, "arrows_ver.xpm");
  toolbar_equate_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Equate",
                                "Set the source area to be the same as the view area", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (toolbar_equate_button, "toolbar_equate_button");
  gtk_widget_ref (toolbar_equate_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "toolbar_equate_button", toolbar_equate_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_equate_button);

  tmp_toolbar_icon = create_pixmap (main_window, "source.xpm");
  toolbar_heuristic_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Heuristic",
                                "Start current heuristic algorithm", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (toolbar_heuristic_button, "toolbar_heuristic_button");
  gtk_widget_ref (toolbar_heuristic_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "toolbar_heuristic_button", toolbar_heuristic_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_heuristic_button);

  tmp_toolbar_icon = create_pixmap (main_window, "stop.xpm");
  toolbar_stop_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Stop",
                                "Stop current heuristic algorithm", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_set_name (toolbar_stop_button, "toolbar_stop_button");
  gtk_widget_ref (toolbar_stop_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "toolbar_stop_button", toolbar_stop_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar_stop_button);
  gtk_widget_set_sensitive (toolbar_stop_button, FALSE);

  main_notebook = gtk_notebook_new ();
  gtk_widget_set_name (main_notebook, "main_notebook");
  gtk_widget_ref (main_notebook);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "main_notebook", main_notebook,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_notebook);
  gtk_box_pack_start (GTK_BOX (vbox1), main_notebook, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (main_notebook), 1);

  patch_box = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (patch_box, "patch_box");
  gtk_widget_ref (patch_box);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "patch_box", patch_box,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (patch_box);
  gtk_container_add (GTK_CONTAINER (main_notebook), patch_box);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox9, "hbox9");
  gtk_widget_ref (hbox9);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "hbox9", hbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (patch_box), hbox9, FALSE, FALSE, 0);

  label1241 = gtk_label_new ("Patch: ");
  gtk_widget_set_name (label1241, "label1241");
  gtk_widget_ref (label1241);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label1241", label1241,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1241);
  gtk_box_pack_start (GTK_BOX (hbox9), label1241, FALSE, FALSE, 0);

  patch_combo = gtk_combo_new ();
  gtk_widget_set_name (patch_combo, "patch_combo");
  gtk_widget_ref (patch_combo);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "patch_combo", patch_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (patch_combo);
  gtk_box_pack_start (GTK_BOX (hbox9), patch_combo, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (patch_combo), TRUE, TRUE);

  patch_combo_entry = GTK_COMBO (patch_combo)->entry;
  gtk_widget_set_name (patch_combo_entry, "patch_combo_entry");
  gtk_widget_ref (patch_combo_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "patch_combo_entry", patch_combo_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (patch_combo_entry);
  gtk_entry_set_editable (GTK_ENTRY (patch_combo_entry), FALSE);

  hbox10 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox10, "hbox10");
  gtk_widget_ref (hbox10);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "hbox10", hbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (hbox9), hbox10, FALSE, FALSE, 0);

  patch_apply_button = gtk_button_new_with_label ("Apply");
  gtk_widget_set_name (patch_apply_button, "patch_apply_button");
  gtk_widget_ref (patch_apply_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "patch_apply_button", patch_apply_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (patch_apply_button);
  gtk_box_pack_start (GTK_BOX (hbox10), patch_apply_button, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, patch_apply_button, "Apply the patch settings", NULL);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow7, "scrolledwindow7");
  gtk_widget_ref (scrolledwindow7);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "scrolledwindow7", scrolledwindow7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow7);
  gtk_box_pack_start (GTK_BOX (patch_box), scrolledwindow7, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow7), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  patch_description = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (patch_description, "patch_description");
  gtk_widget_ref (patch_description);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "patch_description", patch_description,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (patch_description);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), patch_description);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox8, "hbox8");
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 0), hbox8);

  label1240 = gtk_label_new ("Patch");
  gtk_widget_set_name (label1240, "label1240");
  gtk_widget_ref (label1240);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label1240", label1240,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1240);
  gtk_box_pack_start (GTK_BOX (hbox8), label1240, FALSE, FALSE, 0);

  pixmap4 = create_pixmap (main_window, "gnome-db-browser.xpm");
  gtk_widget_set_name (pixmap4, "pixmap4");
  gtk_widget_ref (pixmap4);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "pixmap4", pixmap4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap4);
  gtk_box_pack_start (GTK_BOX (hbox8), pixmap4, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (main_notebook), vbox2);

  table1 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox2), table1, FALSE, FALSE, 0);

  label6 = gtk_label_new ("Componant:");
  gtk_widget_set_name (label6, "label6");
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 1, 0.5);

  transform_componant_entry = gtk_entry_new ();
  gtk_widget_set_name (transform_componant_entry, "transform_componant_entry");
  gtk_widget_ref (transform_componant_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "transform_componant_entry", transform_componant_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (transform_componant_entry);
  gtk_table_attach (GTK_TABLE (table1), transform_componant_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_editable (GTK_ENTRY (transform_componant_entry), FALSE);

  button1 = gtk_button_new_with_label ("Choose...");
  gtk_widget_set_name (button1, "button1");
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_table_attach (GTK_TABLE (table1), button1, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, button1, "Choose a different transform componant", NULL);

  button3 = gtk_button_new_with_label ("Choose...");
  gtk_widget_set_name (button3, "button3");
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_table_attach (GTK_TABLE (table1), button3, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, button3, "Choose a different user interface componant", NULL);

  label7 = gtk_label_new ("Interface:");
  gtk_widget_set_name (label7, "label7");
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 1, 0.5);

  transform_interface_entry = gtk_entry_new ();
  gtk_widget_set_name (transform_interface_entry, "transform_interface_entry");
  gtk_widget_ref (transform_interface_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "transform_interface_entry", transform_interface_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (transform_interface_entry);
  gtk_table_attach (GTK_TABLE (table1), transform_interface_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_editable (GTK_ENTRY (transform_interface_entry), FALSE);

  transform_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (transform_frame, "transform_frame");
  gtk_widget_ref (transform_frame);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "transform_frame", transform_frame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (transform_frame);
  gtk_box_pack_start (GTK_BOX (vbox2), transform_frame, TRUE, TRUE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox6, "hbox6");
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 1), hbox6);

  label1237 = gtk_label_new ("Transform");
  gtk_widget_set_name (label1237, "label1237");
  gtk_widget_ref (label1237);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label1237", label1237,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1237);
  gtk_box_pack_start (GTK_BOX (hbox6), label1237, FALSE, FALSE, 0);

  pixmap2 = create_pixmap (main_window, "24_sort_ascending.xpm");
  gtk_widget_set_name (pixmap2, "pixmap2");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox6), pixmap2, TRUE, TRUE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (main_notebook), vbox5);

  table7 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table7, "table7");
  gtk_widget_ref (table7);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "table7", table7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table7);
  gtk_box_pack_start (GTK_BOX (vbox5), table7, FALSE, FALSE, 0);

  label23 = gtk_label_new ("Componant:");
  gtk_widget_set_name (label23, "label23");
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table7), label23, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 1, 0.5);

  heuristic_componant_entry = gtk_entry_new ();
  gtk_widget_set_name (heuristic_componant_entry, "heuristic_componant_entry");
  gtk_widget_ref (heuristic_componant_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "heuristic_componant_entry", heuristic_componant_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (heuristic_componant_entry);
  gtk_table_attach (GTK_TABLE (table7), heuristic_componant_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_editable (GTK_ENTRY (heuristic_componant_entry), FALSE);

  label24 = gtk_label_new ("Interface:");
  gtk_widget_set_name (label24, "label24");
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table7), label24, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 1, 0.5);

  heuristic_interface_entry = gtk_entry_new ();
  gtk_widget_set_name (heuristic_interface_entry, "heuristic_interface_entry");
  gtk_widget_ref (heuristic_interface_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "heuristic_interface_entry", heuristic_interface_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (heuristic_interface_entry);
  gtk_table_attach (GTK_TABLE (table7), heuristic_interface_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_editable (GTK_ENTRY (heuristic_interface_entry), FALSE);

  button37 = gtk_button_new_with_label ("Choose...");
  gtk_widget_set_name (button37, "button37");
  gtk_widget_ref (button37);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "button37", button37,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button37);
  gtk_table_attach (GTK_TABLE (table7), button37, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, button37, "Choose a different heuristic componant", NULL);

  button38 = gtk_button_new_with_label ("Choose...");
  gtk_widget_set_name (button38, "button38");
  gtk_widget_ref (button38);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "button38", button38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button38);
  gtk_table_attach (GTK_TABLE (table7), button38, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, button38, "Choose a different user interface componant", NULL);

  heuristic_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (heuristic_frame, "heuristic_frame");
  gtk_widget_ref (heuristic_frame);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "heuristic_frame", heuristic_frame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (heuristic_frame);
  gtk_box_pack_start (GTK_BOX (vbox5), heuristic_frame, TRUE, TRUE, 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 2), hbox5);

  label1236 = gtk_label_new ("Heuristic");
  gtk_widget_set_name (label1236, "label1236");
  gtk_widget_ref (label1236);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label1236", label1236,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1236);
  gtk_box_pack_start (GTK_BOX (hbox5), label1236, FALSE, FALSE, 0);

  pixmap3 = create_pixmap (main_window, "gear_small.xpm");
  gtk_widget_set_name (pixmap3, "pixmap3");
  gtk_widget_ref (pixmap3);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "pixmap3", pixmap3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap3);
  gtk_box_pack_start (GTK_BOX (hbox5), pixmap3, TRUE, TRUE, 0);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (main_notebook), vbox6);

  table8 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table8, "table8");
  gtk_widget_ref (table8);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "table8", table8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table8);
  gtk_box_pack_start (GTK_BOX (vbox6), table8, FALSE, FALSE, 0);

  label25 = gtk_label_new ("Componant:");
  gtk_widget_set_name (label25, "label25");
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table8), label25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 1, 0.5);

  fitness_componant_entry = gtk_entry_new ();
  gtk_widget_set_name (fitness_componant_entry, "fitness_componant_entry");
  gtk_widget_ref (fitness_componant_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "fitness_componant_entry", fitness_componant_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fitness_componant_entry);
  gtk_table_attach (GTK_TABLE (table8), fitness_componant_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_editable (GTK_ENTRY (fitness_componant_entry), FALSE);

  label26 = gtk_label_new ("Interface:");
  gtk_widget_set_name (label26, "label26");
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table8), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 1, 0.5);

  fitness_interface_entry = gtk_entry_new ();
  gtk_widget_set_name (fitness_interface_entry, "fitness_interface_entry");
  gtk_widget_ref (fitness_interface_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "fitness_interface_entry", fitness_interface_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fitness_interface_entry);
  gtk_table_attach (GTK_TABLE (table8), fitness_interface_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_editable (GTK_ENTRY (fitness_interface_entry), FALSE);

  button39 = gtk_button_new_with_label ("Choose...");
  gtk_widget_set_name (button39, "button39");
  gtk_widget_ref (button39);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "button39", button39,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button39);
  gtk_table_attach (GTK_TABLE (table8), button39, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, button39, "Choose a different fitness componant", NULL);

  button40 = gtk_button_new_with_label ("Choose...");
  gtk_widget_set_name (button40, "button40");
  gtk_widget_ref (button40);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "button40", button40,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button40);
  gtk_table_attach (GTK_TABLE (table8), button40, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, button40, "Choose a different user interface componant", NULL);

  fitness_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (fitness_frame, "fitness_frame");
  gtk_widget_ref (fitness_frame);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "fitness_frame", fitness_frame,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fitness_frame);
  gtk_box_pack_start (GTK_BOX (vbox6), fitness_frame, TRUE, TRUE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 3), hbox4);

  fitness_label = gtk_label_new ("Fitness");
  gtk_widget_set_name (fitness_label, "fitness_label");
  gtk_widget_ref (fitness_label);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "fitness_label", fitness_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fitness_label);
  gtk_box_pack_start (GTK_BOX (hbox4), fitness_label, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (fitness_label), 7.45058e-09, 0.5);

  pixmap1 = create_pixmap (main_window, "function_selector.xpm");
  gtk_widget_set_name (pixmap1, "pixmap1");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox4), pixmap1, TRUE, TRUE, 0);

  label4 = gtk_label_new ("Source");
  gtk_widget_set_name (label4, "label4");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox1), label4, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  source_text = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (source_text, "source_text");
  gtk_widget_ref (source_text);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "source_text", source_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (source_text);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), source_text);
  gtk_text_set_editable (GTK_TEXT (source_text), TRUE);

  label5 = gtk_label_new ("View");
  gtk_widget_set_name (label5, "label5");
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (vbox1), label5, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  view_text = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (view_text, "view_text");
  gtk_widget_ref (view_text);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "view_text", view_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (view_text);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), view_text);

  statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar, "statusbar");
  gtk_widget_ref (statusbar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "statusbar", statusbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (main_window), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (open3), "activate",
                      GTK_SIGNAL_FUNC (on_open),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save), "activate",
                      GTK_SIGNAL_FUNC (on_save),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit2), "activate",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (guile_shell), "activate",
                      GTK_SIGNAL_FUNC (on_guile_shell_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_about_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_open_button), "clicked",
                      GTK_SIGNAL_FUNC (on_open),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_save_button), "clicked",
                      GTK_SIGNAL_FUNC (on_save),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_equate_button), "clicked",
                      GTK_SIGNAL_FUNC (on_equate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_heuristic_button), "clicked",
                      GTK_SIGNAL_FUNC (on_start_heuristic),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar_stop_button), "clicked",
                      GTK_SIGNAL_FUNC (on_stop_heuristic),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (patch_combo_entry), "changed",
                      GTK_SIGNAL_FUNC (on_patch_combo_entry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (patch_apply_button), "clicked",
                      GTK_SIGNAL_FUNC (on_patch_apply_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_choose_componant_button_clicked),
                      "transform_componant");
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_choose_componant_button_clicked),
                      "transform_interface");
  gtk_signal_connect (GTK_OBJECT (button37), "clicked",
                      GTK_SIGNAL_FUNC (on_choose_componant_button_clicked),
                      "heuristic_componant");
  gtk_signal_connect (GTK_OBJECT (button38), "clicked",
                      GTK_SIGNAL_FUNC (on_choose_componant_button_clicked),
                      "heuristic_interface");
  gtk_signal_connect (GTK_OBJECT (button39), "clicked",
                      GTK_SIGNAL_FUNC (on_choose_componant_button_clicked),
                      "fitness_componant");
  gtk_signal_connect (GTK_OBJECT (button40), "clicked",
                      GTK_SIGNAL_FUNC (on_choose_componant_button_clicked),
                      "fitness_interface");
  gtk_signal_connect (GTK_OBJECT (source_text), "changed",
                      GTK_SIGNAL_FUNC (on_source_text_changed),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (main_window), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_about_dialog (void)
{
  GtkWidget *about_dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *frame4;
  GtkWidget *scrolledwindow3;
  GtkWidget *about_dialog_text;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbox1;
  GtkWidget *hseparator1;
  GtkWidget *button31;
  GtkWidget *hseparator2;

  about_dialog = gtk_dialog_new ();
  gtk_widget_set_name (about_dialog, "about_dialog");
  gtk_object_set_data (GTK_OBJECT (about_dialog), "about_dialog", about_dialog);
  gtk_window_set_title (GTK_WINDOW (about_dialog), "About");
  GTK_WINDOW (about_dialog)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (about_dialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (about_dialog), TRUE);

  dialog_vbox1 = GTK_DIALOG (about_dialog)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_object_set_data (GTK_OBJECT (about_dialog), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  frame4 = gtk_frame_new ("Crank");
  gtk_widget_set_name (frame4, "frame4");
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (about_dialog), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), frame4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 3);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (about_dialog), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (frame4), scrolledwindow3);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow3), 2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  about_dialog_text = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (about_dialog_text, "about_dialog_text");
  gtk_widget_ref (about_dialog_text);
  gtk_object_set_data_full (GTK_OBJECT (about_dialog), "about_dialog_text", about_dialog_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about_dialog_text);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), about_dialog_text);
  gtk_widget_set_usize (about_dialog_text, 320, 146);
  GTK_WIDGET_UNSET_FLAGS (about_dialog_text, GTK_CAN_FOCUS);

  dialog_action_area1 = GTK_DIALOG (about_dialog)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_object_set_data (GTK_OBJECT (about_dialog), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (about_dialog), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbox1, TRUE, TRUE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (about_dialog), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (hbox1), hseparator1, TRUE, TRUE, 0);

  button31 = gtk_button_new_with_label ("OK");
  gtk_widget_set_name (button31, "button31");
  gtk_widget_ref (button31);
  gtk_object_set_data_full (GTK_OBJECT (about_dialog), "button31", button31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button31);
  gtk_box_pack_start (GTK_BOX (hbox1), button31, TRUE, TRUE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator2, "hseparator2");
  gtk_widget_ref (hseparator2);
  gtk_object_set_data_full (GTK_OBJECT (about_dialog), "hseparator2", hseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (hbox1), hseparator2, TRUE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (about_dialog), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button31), "clicked",
                      GTK_SIGNAL_FUNC (on_about_ok_button_clicked),
                      NULL);

  return about_dialog;
}

GtkWidget*
create_componant_choice_dialog (void)
{
  GtkWidget *componant_choice_dialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *hpaned1;
  GtkWidget *scrolledwindow4;
  GtkWidget *componant_choice_list;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *componant_choice_table;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *componant_choice_label_applies_to;
  GtkWidget *componant_choice_source;
  GtkWidget *componant_choice_applies_to;
  GtkWidget *scrolledwindow5;
  GtkWidget *componant_choice_description;
  GtkWidget *componant_choice_name;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbox2;
  GtkWidget *hseparator3;
  GtkWidget *button32;
  GtkWidget *hseparator4;
  GtkWidget *button33;
  GtkWidget *hseparator5;

  componant_choice_dialog = gtk_dialog_new ();
  gtk_widget_set_name (componant_choice_dialog, "componant_choice_dialog");
  gtk_object_set_data (GTK_OBJECT (componant_choice_dialog), "componant_choice_dialog", componant_choice_dialog);
  gtk_window_set_title (GTK_WINDOW (componant_choice_dialog), "Choose a componant");
  gtk_window_set_modal (GTK_WINDOW (componant_choice_dialog), TRUE);

  dialog_vbox2 = GTK_DIALOG (componant_choice_dialog)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_object_set_data (GTK_OBJECT (componant_choice_dialog), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_set_name (hpaned1, "hpaned1");
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), hpaned1, TRUE, TRUE, 0);
  gtk_widget_set_usize (hpaned1, 636, -2);
  gtk_container_set_border_width (GTK_CONTAINER (hpaned1), 4);
  gtk_paned_set_handle_size (GTK_PANED (hpaned1), 11);
  gtk_paned_set_gutter_size (GTK_PANED (hpaned1), 15);
  gtk_paned_set_position (GTK_PANED (hpaned1), 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow4, "scrolledwindow4");
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_paned_pack1 (GTK_PANED (hpaned1), scrolledwindow4, TRUE, FALSE);
  gtk_widget_set_usize (scrolledwindow4, 182, -2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  componant_choice_list = gtk_clist_new (2);
  gtk_widget_set_name (componant_choice_list, "componant_choice_list");
  gtk_widget_ref (componant_choice_list);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "componant_choice_list", componant_choice_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (componant_choice_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), componant_choice_list);
  gtk_clist_set_column_width (GTK_CLIST (componant_choice_list), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (componant_choice_list), 1, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (componant_choice_list));

  label27 = gtk_label_new ("label27");
  gtk_widget_set_name (label27, "label27");
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_clist_set_column_widget (GTK_CLIST (componant_choice_list), 0, label27);

  label28 = gtk_label_new ("label28");
  gtk_widget_set_name (label28, "label28");
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_clist_set_column_widget (GTK_CLIST (componant_choice_list), 1, label28);

  componant_choice_table = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (componant_choice_table, "componant_choice_table");
  gtk_widget_ref (componant_choice_table);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "componant_choice_table", componant_choice_table,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (componant_choice_table);
  gtk_paned_pack2 (GTK_PANED (hpaned1), componant_choice_table, TRUE, TRUE);

  label19 = gtk_label_new ("Name:");
  gtk_widget_set_name (label19, "label19");
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (componant_choice_table), label19, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 1, 0.5);

  label20 = gtk_label_new ("Source: ");
  gtk_widget_set_name (label20, "label20");
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (componant_choice_table), label20, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 1, 0.5);

  label21 = gtk_label_new ("Description:");
  gtk_widget_set_name (label21, "label21");
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (componant_choice_table), label21, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 1, 0.5);

  componant_choice_label_applies_to = gtk_label_new ("Applies to:");
  gtk_widget_set_name (componant_choice_label_applies_to, "componant_choice_label_applies_to");
  gtk_widget_ref (componant_choice_label_applies_to);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "componant_choice_label_applies_to", componant_choice_label_applies_to,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (componant_choice_label_applies_to);
  gtk_table_attach (GTK_TABLE (componant_choice_table), componant_choice_label_applies_to, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (componant_choice_label_applies_to), 1, 0.5);

  componant_choice_source = gtk_label_new ("");
  gtk_widget_set_name (componant_choice_source, "componant_choice_source");
  gtk_widget_ref (componant_choice_source);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "componant_choice_source", componant_choice_source,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (componant_choice_source);
  gtk_table_attach (GTK_TABLE (componant_choice_table), componant_choice_source, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_line_wrap (GTK_LABEL (componant_choice_source), TRUE);
  gtk_misc_set_alignment (GTK_MISC (componant_choice_source), 0, 0.5);

  componant_choice_applies_to = gtk_label_new ("");
  gtk_widget_set_name (componant_choice_applies_to, "componant_choice_applies_to");
  gtk_widget_ref (componant_choice_applies_to);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "componant_choice_applies_to", componant_choice_applies_to,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (componant_choice_applies_to);
  gtk_table_attach (GTK_TABLE (componant_choice_table), componant_choice_applies_to, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_line_wrap (GTK_LABEL (componant_choice_applies_to), TRUE);
  gtk_misc_set_alignment (GTK_MISC (componant_choice_applies_to), 0, 0.5);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow5, "scrolledwindow5");
  gtk_widget_ref (scrolledwindow5);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "scrolledwindow5", scrolledwindow5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow5);
  gtk_table_attach (GTK_TABLE (componant_choice_table), scrolledwindow5, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  componant_choice_description = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (componant_choice_description, "componant_choice_description");
  gtk_widget_ref (componant_choice_description);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "componant_choice_description", componant_choice_description,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (componant_choice_description);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), componant_choice_description);
  GTK_WIDGET_UNSET_FLAGS (componant_choice_description, GTK_CAN_FOCUS);

  componant_choice_name = gtk_label_new ("");
  gtk_widget_set_name (componant_choice_name, "componant_choice_name");
  gtk_widget_ref (componant_choice_name);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "componant_choice_name", componant_choice_name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (componant_choice_name);
  gtk_table_attach (GTK_TABLE (componant_choice_table), componant_choice_name, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_line_wrap (GTK_LABEL (componant_choice_name), TRUE);
  gtk_misc_set_alignment (GTK_MISC (componant_choice_name), 0, 0.5);

  dialog_action_area2 = GTK_DIALOG (componant_choice_dialog)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_object_set_data (GTK_OBJECT (componant_choice_dialog), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  hbox2 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), hbox2, TRUE, TRUE, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator3, "hseparator3");
  gtk_widget_ref (hseparator3);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "hseparator3", hseparator3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (hbox2), hseparator3, TRUE, TRUE, 0);

  button32 = gtk_button_new_with_label ("OK");
  gtk_widget_set_name (button32, "button32");
  gtk_widget_ref (button32);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "button32", button32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button32);
  gtk_box_pack_start (GTK_BOX (hbox2), button32, TRUE, TRUE, 0);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator4, "hseparator4");
  gtk_widget_ref (hseparator4);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "hseparator4", hseparator4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (hbox2), hseparator4, TRUE, TRUE, 0);

  button33 = gtk_button_new_with_label ("Cancel");
  gtk_widget_set_name (button33, "button33");
  gtk_widget_ref (button33);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "button33", button33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button33);
  gtk_box_pack_start (GTK_BOX (hbox2), button33, TRUE, TRUE, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator5, "hseparator5");
  gtk_widget_ref (hseparator5);
  gtk_object_set_data_full (GTK_OBJECT (componant_choice_dialog), "hseparator5", hseparator5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator5);
  gtk_box_pack_start (GTK_BOX (hbox2), hseparator5, TRUE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (componant_choice_list), "select_row",
                      GTK_SIGNAL_FUNC (on_componant_choice_list_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button32), "clicked",
                      GTK_SIGNAL_FUNC (on_componant_choice_ok_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button33), "clicked",
                      GTK_SIGNAL_FUNC (on_componant_choice_cancel_button_clicked),
                      NULL);

  return componant_choice_dialog;
}

GtkWidget*
create_open_fileselection (void)
{
  GtkWidget *open_fileselection;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  open_fileselection = gtk_file_selection_new ("Open file into source area");
  gtk_widget_set_name (open_fileselection, "open_fileselection");
  gtk_object_set_data (GTK_OBJECT (open_fileselection), "open_fileselection", open_fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (open_fileselection), 10);
  GTK_WINDOW (open_fileselection)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (open_fileselection), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (open_fileselection), TRUE);
  gtk_file_selection_hide_fileop_buttons (GTK_FILE_SELECTION (open_fileselection));

  ok_button1 = GTK_FILE_SELECTION (open_fileselection)->ok_button;
  gtk_widget_set_name (ok_button1, "ok_button1");
  gtk_object_set_data (GTK_OBJECT (open_fileselection), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (open_fileselection)->cancel_button;
  gtk_widget_set_name (cancel_button1, "cancel_button1");
  gtk_object_set_data (GTK_OBJECT (open_fileselection), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (open_fileselection), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_open_file_ok_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_open_file_cancel_button_clicked),
                      NULL);

  return open_fileselection;
}

GtkWidget*
create_save_fileselection (void)
{
  GtkWidget *save_fileselection;
  GtkWidget *button44;
  GtkWidget *button45;

  save_fileselection = gtk_file_selection_new ("Save view area as...");
  gtk_widget_set_name (save_fileselection, "save_fileselection");
  gtk_object_set_data (GTK_OBJECT (save_fileselection), "save_fileselection", save_fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (save_fileselection), 10);
  GTK_WINDOW (save_fileselection)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (save_fileselection), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (save_fileselection), TRUE);

  button44 = GTK_FILE_SELECTION (save_fileselection)->ok_button;
  gtk_widget_set_name (button44, "button44");
  gtk_object_set_data (GTK_OBJECT (save_fileselection), "button44", button44);
  gtk_widget_show (button44);
  GTK_WIDGET_SET_FLAGS (button44, GTK_CAN_DEFAULT);

  button45 = GTK_FILE_SELECTION (save_fileselection)->cancel_button;
  gtk_widget_set_name (button45, "button45");
  gtk_object_set_data (GTK_OBJECT (save_fileselection), "button45", button45);
  gtk_widget_show (button45);
  GTK_WIDGET_SET_FLAGS (button45, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (save_fileselection), "delete_event",
                      GTK_SIGNAL_FUNC (gtk_widget_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button44), "clicked",
                      GTK_SIGNAL_FUNC (on_save_file_ok_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button45), "clicked",
                      GTK_SIGNAL_FUNC (on_save_file_cancel_button_clicked),
                      NULL);

  return save_fileselection;
}

GtkWidget*
create_heuristic_log (void)
{
  GtkWidget *heuristic_log;
  GtkWidget *vbox7;
  GtkWidget *vbox9;
  GtkWidget *scrolledwindow6;
  GtkWidget *heuristic_log_text;
  GtkWidget *heuristic_log_progress_bar;
  GtkWidget *hbox3;
  GtkWidget *hseparator6;
  GtkWidget *button46;
  GtkWidget *hseparator7;

  heuristic_log = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_widget_set_name (heuristic_log, "heuristic_log");
  gtk_object_set_data (GTK_OBJECT (heuristic_log), "heuristic_log", heuristic_log);
  gtk_window_set_title (GTK_WINDOW (heuristic_log), "Heuristic Messages");

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox7, "vbox7");
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (heuristic_log), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (heuristic_log), vbox7);

  vbox9 = gtk_vbox_new (FALSE, 18);
  gtk_widget_set_name (vbox9, "vbox9");
  gtk_widget_ref (vbox9);
  gtk_object_set_data_full (GTK_OBJECT (heuristic_log), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (vbox7), vbox9, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox9), 22);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow6, "scrolledwindow6");
  gtk_widget_ref (scrolledwindow6);
  gtk_object_set_data_full (GTK_OBJECT (heuristic_log), "scrolledwindow6", scrolledwindow6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow6);
  gtk_box_pack_start (GTK_BOX (vbox9), scrolledwindow6, TRUE, TRUE, 0);
  gtk_widget_set_usize (scrolledwindow6, 328, 206);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  heuristic_log_text = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (heuristic_log_text, "heuristic_log_text");
  gtk_widget_ref (heuristic_log_text);
  gtk_object_set_data_full (GTK_OBJECT (heuristic_log), "heuristic_log_text", heuristic_log_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (heuristic_log_text);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), heuristic_log_text);
  GTK_WIDGET_UNSET_FLAGS (heuristic_log_text, GTK_CAN_FOCUS);

  heuristic_log_progress_bar = gtk_progress_bar_new ();
  gtk_widget_set_name (heuristic_log_progress_bar, "heuristic_log_progress_bar");
  gtk_widget_ref (heuristic_log_progress_bar);
  gtk_object_set_data_full (GTK_OBJECT (heuristic_log), "heuristic_log_progress_bar", heuristic_log_progress_bar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (heuristic_log_progress_bar);
  gtk_box_pack_start (GTK_BOX (vbox9), heuristic_log_progress_bar, FALSE, FALSE, 0);
  gtk_progress_set_show_text (GTK_PROGRESS (heuristic_log_progress_bar), TRUE);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (heuristic_log), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox3, FALSE, TRUE, 0);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator6, "hseparator6");
  gtk_widget_ref (hseparator6);
  gtk_object_set_data_full (GTK_OBJECT (heuristic_log), "hseparator6", hseparator6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator6);
  gtk_box_pack_start (GTK_BOX (hbox3), hseparator6, TRUE, TRUE, 0);

  button46 = gtk_button_new_with_label ("Close");
  gtk_widget_set_name (button46, "button46");
  gtk_widget_ref (button46);
  gtk_object_set_data_full (GTK_OBJECT (heuristic_log), "button46", button46,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button46);
  gtk_box_pack_start (GTK_BOX (hbox3), button46, FALSE, TRUE, 0);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator7, "hseparator7");
  gtk_widget_ref (hseparator7);
  gtk_object_set_data_full (GTK_OBJECT (heuristic_log), "hseparator7", hseparator7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator7);
  gtk_box_pack_start (GTK_BOX (hbox3), hseparator7, TRUE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (heuristic_log), "delete_event",
                      GTK_SIGNAL_FUNC (on_heuristic_log_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button46), "clicked",
                      GTK_SIGNAL_FUNC (on_heuristic_log_delete_event),
                      NULL);

  return heuristic_log;
}

